version: '3'
services:
    payara-full:
        build: mypayara-full
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - /opt/payara41/bin/asadmin
            - start-domain
            - -v
        volumes:
            - ./data/payara:/opt/payara41/glassfish/domains/domain1/autodeploy
        depends_on:
            - db
            - dynamodb

    db:
        image: postgres:10
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - "5433:5432"
        volumes:
            - ./data/pgdata:/var/lib/postgresql/data/pgdata

    dynamodb:
        ports:
          - "8000:8000"
        expose:
          - "8000"
        command: -sharedDb -port 8000
        image: cnadiminti/dynamodb-local
